/**
 * Catalog data for BotanIA — pure static data, no state.
 * Extracted from game-store.ts for maintainability.
 *
 * This file contains: seed shops, seed varieties, plantule catalogs,
 * chambre models, mini-serre constants, equipment cards, and utility functions.
 */

import { type PlantState } from "@/lib/ai-engine";

// ═══ UID Helper ═══
function uid(): string {
  return Math.random().toString(36).slice(2, 10) + Date.now().toString(36).slice(-4);
}

export const MINI_SERRE_ROWS = 6;
export const MINI_SERRE_COLS = 4;
export const MINI_SERRE_PRICE = 120;
export const MINI_SERRE_WIDTH_CM = 20;
export const MINI_SERRE_DEPTH_CM = 32.5;

// ═══ Chambre de Culture ═══

export interface ChambreModel {
  id: string;
  name: string;
  widthCm: number;
  heightCm: number;
  depthCm: number;
  maxMiniSerres: number;
  price: number;
  image: string;
  emoji: string;
  description: string;
  color: string;
}

export const CHAMBRE_CATALOG: ChambreModel[] = [
  {
    id: "chambre-small",
    name: "Chambre 60×60",
    widthCm: 60,
    heightCm: 140,
    depthCm: 60,
    maxMiniSerres: 2,
    price: 200,
    image: "/cards/card-chambre-small.png",
    emoji: "🏠",
    description: "Chambre de culture compacte idéale pour débuter. 60×60×140cm. Accueille 2 mini serres.",
    color: "from-green-100 to-emerald-100",
  },
  {
    id: "chambre-medium",
    name: "Chambre 80×80",
    widthCm: 80,
    heightCm: 160,
    depthCm: 80,
    maxMiniSerres: 4,
    price: 350,
    image: "/cards/card-chambre-medium.png",
    emoji: "🏭",
    description: "Chambre de culture intermédiaire pour jardiniers confirmés. 80×80×160cm. Accueille 4 mini serres.",
    color: "from-emerald-100 to-teal-100",
  },
  {
    id: "chambre-large",
    name: "Chambre 120×120",
    widthCm: 120,
    heightCm: 200,
    depthCm: 120,
    maxMiniSerres: 6,
    price: 550,
    image: "/cards/card-chambre-large.png",
    emoji: "🏗️",
    description: "Chambre de culture professionnelle. 120×120×200cm. Accueille 6 mini serres pour production intensive.",
    color: "from-teal-100 to-cyan-100",
  },
];

export interface MiniSerre {
  id: string;
  slots: (PlantState | null)[][]; // 6 rows × 4 cols
}

export function createEmptyMiniSerre(): MiniSerre {
  return {
    id: uid(),
    slots: Array.from({ length: MINI_SERRE_ROWS }, () =>
      Array.from({ length: MINI_SERRE_COLS }, () => null)
    ),
  };
}

// ═══ Étagères & Plateaux (potted plantule storage) ═══

export const PLATEAU_ROWS = 5;
export const PLATEAU_COLS = 4; // 5 × 4 = 20 slots per plateau
export const ETAGERE_DEFAULT_PLATEAUX = 2;
export const ETAGERE_MAX_PLATEAUX = 3;
export const ETAGERE_PRICE = 150;
export const PLATEAU_ADD_PRICE = 50;

export interface Plateau {
  id: string;
  slots: (PlantState | null)[][]; // 5 rows × 4 cols = 20 slots
}

export interface Etagere {
  id: string;
  plateaux: Plateau[];
}

export function createEmptyPlateau(): Plateau {
  return {
    id: uid(),
    slots: Array.from({ length: PLATEAU_ROWS }, () =>
      Array.from({ length: PLATEAU_COLS }, () => null)
    ),
  };
}

export function createEmptyEtagere(numPlateaux: number = ETAGERE_DEFAULT_PLATEAUX): Etagere {
  return {
    id: uid(),
    plateaux: Array.from({ length: numPlateaux }, () => createEmptyPlateau()),
  };
}

// ═══ Seed Shop System (multi-shop varieties) ═══

export interface SeedShop {
  id: string;
  name: string;
  emoji: string;
  color: string;
  borderColor: string;
  image: string;
  description: string;
}

export interface SeedVariety {
  id: string;
  plantDefId: string;
  shopId: string;
  name: string;
  emoji: string;
  price: number;
  grams: number;
  seedCount?: number; // Nombre de graines dans le paquet (optionnel pour compatibilité)
  description: string;
  image: string;
  unlocked: boolean;
  stageDurations: [number, number, number, number];
  realDaysToHarvest: number;
  optimalTemp: [number, number];
  waterNeed: number;
  lightNeed: number;
}

export const SEED_SHOPS: SeedShop[] = [
  {
    id: "vilmorin",
    name: "Vilmorin",
    emoji: "🌱",
    color: "from-red-50 to-orange-50",
    borderColor: "border-red-200",
    image: "/assets/shops/card-shop-vilmorin.png",
    description: "Jardinier depuis 1814 — Leader français des semences potagères et fleurs",
  },
  {
    id: "clause",
    name: "Clause",
    emoji: "🌺",
    color: "from-purple-50 to-pink-50",
    borderColor: "border-purple-200",
    image: "/assets/shops/card-shop-clause.png",
    description: "Semences et plants potagers — Qualité professionnelle",
  },
  // Boutiques Bio & Paysannes
  {
    id: "kokopelli",
    name: "Kokopelli",
    emoji: "\ud83c\udf31",
    color: "from-green-50 to-emerald-50",
    borderColor: "border-green-300",
    image: "/assets/shops/card-shop-kokopelli.png",
    description: "Semences biologiques, libres de droits et reproductibles depuis +25 ans",
  },
  {
    id: "lebiau",
    name: "Le Biau Germe",
    emoji: "\ud83c\udf3e",
    color: "from-yellow-50 to-amber-50",
    borderColor: "border-amber-300",
    image: "/assets/shops/card-shop-lebiau.png",
    description: "Semences paysannes biologiques depuis 1981 - 12 fermes en France",
  },
  {
    id: "saintemarthe",
    name: "Ferme de Sainte Marthe",
    emoji: "\ud83c\udfe1",
    color: "from-orange-50 to-red-50",
    borderColor: "border-orange-300",
    image: "/assets/shops/card-shop-sainte-marthe.png",
    description: "Semences biologiques et reproductibles, Patrimoine varietal depuis 1973",
  },
  // Pepinieres & Arbres fruitiers
  {
    id: "guignard",
    name: "Guignard",
    emoji: "🌳",
    color: "from-green-50 to-teal-50",
    borderColor: "border-green-400",
    image: "/assets/shops/card-shop-guignard.png",
    description: "Pepinieriste depuis 1850 — Arbres fruitiers et d'ornement",
  },
  {
    id: "inrae",
    name: "INRAE",
    emoji: "🔬",
    color: "from-blue-50 to-indigo-50",
    borderColor: "border-blue-300",
    image: "/assets/shops/card-shop-inrae.png",
    description: "Institut Recherche Agriculture — Semences forestieres et varietes anciennes",
  },
  {
    id: "pepinieres-bordas",
    name: "Pépinières Bordas",
    emoji: "🌲",
    color: "from-emerald-50 to-teal-50",
    borderColor: "border-emerald-300",
    image: "/assets/shops/card-shop-pepinieres-bordas.png",
    description: "Pépiniériste spécialisé en arbres fruitiers et d'ornement depuis 1920",
  },
  {
    id: "arbres-tissot",
    name: "Arbres Tissot",
    emoji: "🌴",
    color: "from-lime-50 to-green-50",
    borderColor: "border-lime-400",
    image: "/assets/shops/card-shop-arbres-tissot.png",
    description: "Spécialiste pommiers et poiriers — Vergers et arbres d'ornement",
  },
  {
    id: "fruitiers-forest",
    name: "Fruitiers Forest",
    emoji: "🍎",
    color: "from-red-50 to-pink-50",
    borderColor: "border-red-300",
    image: "/assets/shops/card-shop-fruitiers-forest.png",
    description: "Vergers et petits fruits — Gamme complète d'arbres fruitiers",
  },
  // ═══ Achats Locaux & Pepinieres ═══
  {
    id: "pepiniere-locale",
    name: "Pépinière",
    emoji: "🏡",
    color: "from-amber-50 to-yellow-50",
    borderColor: "border-amber-300",
    image: "/assets/shops/card-shop-pepiniere-locale.png",
    description: "Plants élevés à la ferme — Arbres, arbustes et plantules de saison",
  },
  {
    id: "les-pepineres-quissac",
    name: "Les Pépinières Quissac",
    emoji: "🌿",
    color: "from-green-50 to-emerald-50",
    borderColor: "border-emerald-300",
    image: "/assets/shops/card-shop-quissac.png",
    description: "Pépiniériste local — Plants et arbustes cultivés en Occitanie",
  },
  {
    id: "leaderplant",
    name: "Leaderplant",
    emoji: "🌳",
    color: "from-teal-50 to-cyan-50",
    borderColor: "border-teal-300",
    image: "/assets/shops/card-shop-leaderplant.png",
    description: "Pépinière spécialisée — Fruitiers, petits fruits et plantes vivaces",
  },
  {
    id: "marche-producteurs",
    name: "Marché Producteurs",
    emoji: "🧺",
    color: "from-orange-50 to-red-50",
    borderColor: "border-orange-300",
    image: "/assets/shops/card-shop-marche.png",
    description: "Ventes directes — Plants et plantules de maraîchers locaux",
  },
  {
    id: "jardin-partage",
    name: "Jardin Partagé",
    emoji: "🌾",
    color: "from-green-50 to-emerald-50",
    borderColor: "border-green-300",
    image: "/assets/shops/card-shop-jardin-partage.png",
    description: "Échange entre jardiniers — Plants et semis cultivés localement",
  },
  // ═══ Bientôt disponible ═══
  {
    id: "bientot-dispo",
    name: "Bientôt dispo",
    emoji: "🔜",
    color: "from-stone-100 to-stone-200",
    borderColor: "border-stone-300",
    image: "/assets/shops/card-shop-placeholder.png",
    description: "Ce magasin arrive bientôt — Restez attentifs !",
  },
  // ═══ Magasins Plantules ═══
  {
    id: "jardiland",
    name: "Jardiland",
    emoji: "🏡",
    color: "from-green-50 to-emerald-50",
    borderColor: "border-green-300",
    image: "/assets/shops/card-shop-jardiland.png",
    description: "Le spécialiste jardin — Plants et plantules de saison",
  },
  {
    id: "gamm-vert",
    name: "Gamm Vert",
    emoji: "🌿",
    color: "from-lime-50 to-green-50",
    borderColor: "border-lime-300",
    image: "/assets/shops/card-shop-gamm-vert.png",
    description: "Proche de chez vous — Gamme complète jardin et extérieur",
  },
  {
    id: "esat-antes",
    name: 'E.S.A.T. "Les Antes"',
    emoji: "🌻",
    color: "from-yellow-50 to-amber-50",
    borderColor: "border-amber-300",
    image: "/assets/shops/card-shop-esat-antes.png",
    description: "Etablissement et Service d'Aide par le Travail — Plants adaptés",
  },
  {
    id: "jardi-leclerc",
    name: "Jardi E.Leclerc",
    emoji: "🛒",
    color: "from-red-50 to-orange-50",
    borderColor: "border-red-300",
    image: "/assets/shops/card-shop-jardi-leclerc.png",
    description: "Jardin et animalerie — Large choix à petits prix",
  },
];

// ═══ Plantules Locales (pour achats-locaux) ═══
export const PLANTULES_LOCALES: SeedVariety[] = [
  // Tomates locales
  {
    id: "plantule-tomate-coeur-boeuf",
    plantDefId: "tomato",
    shopId: "jardiland",
    name: "Tomate Coeur de Boeuf",
    emoji: "🍅",
    price: 90,
    grams: 0,
    description: "Plantule élevée en local — Variété charnue et parfumée, excellente pour salade",
    image: "/plantules/plantule-tomate-coeur-boeuf.png",
    unlocked: true,
    stageDurations: [8, 22, 20, 45],
    realDaysToHarvest: 95,
    optimalTemp: [16, 28],
    waterNeed: 5.0,
    lightNeed: 8,
  },
  {
    id: "plantule-tomate-ananas",
    plantDefId: "tomato",
    shopId: "jardiland",
    name: "Tomate Ananas",
    emoji: "🍅",
    price: 95,
    grams: 0,
    description: "Plantule locale — Chair jaune orangée, douce et sucrée, variété ancienne",
    image: "/plantules/plantule-tomate-ananas.png",
    unlocked: true,
    stageDurations: [10, 25, 25, 55],
    realDaysToHarvest: 115,
    optimalTemp: [18, 28],
    waterNeed: 5.0,
    lightNeed: 8,
  },
  // Courgettes et squash locaux
  {
    id: "plantule-courgette-rond",
    plantDefId: "zucchini",
    shopId: "jardiland",
    name: "Courgette Ronde de Nice",
    emoji: "🥒",
    price: 75,
    grams: 0,
    description: "Plantule locale — Variété provençale, idéale pour farcir",
    image: "/plantules/plantule-courgette-rond.png",
    unlocked: true,
    stageDurations: [6, 16, 20, 42],
    realDaysToHarvest: 84,
    optimalTemp: [18, 28],
    waterNeed: 5.0,
    lightNeed: 8,
  },
  {
    id: "plantule-potimarron",
    plantDefId: "squash",
    shopId: "jardiland",
    name: "Potimarron",
    emoji: "🎃",
    price: 80,
    grams: 0,
    description: "Plantule locale — Courge douce, chair orangée, excellente conservation",
    image: "/plantules/plantule-potimarron.png",
    unlocked: true,
    stageDurations: [8, 20, 30, 60],
    realDaysToHarvest: 118,
    optimalTemp: [15, 26],
    waterNeed: 4.5,
    lightNeed: 7,
  },
  // Poivrons et piments locaux
  {
    id: "plantule-poivron-corne",
    plantDefId: "pepper",
    shopId: "jardiland",
    name: "Poivron Corne de Boeuf",
    emoji: "🌶️",
    price: 85,
    grams: 0,
    description: "Plantule locale — Chair épaisse, doux, idéal pourfarcir",
    image: "/plantules/plantule-poivron-corne.png",
    unlocked: true,
    stageDurations: [10, 26, 26, 58],
    realDaysToHarvest: 120,
    optimalTemp: [20, 28],
    waterNeed: 5.0,
    lightNeed: 8,
  },
  {
    id: "plantule-piment-espelette",
    plantDefId: "pepper",
    shopId: "gamm-vert",
    name: "Piment d'Espelette",
    emoji: "🌶️",
    price: 95,
    grams: 0,
    description: "Plantule du Pays Basque — AOP, saveur douce et légèrement épicée",
    image: "/plantules/plantule-piment-espelette.png",
    unlocked: true,
    stageDurations: [12, 28, 30, 65],
    realDaysToHarvest: 135,
    optimalTemp: [20, 30],
    waterNeed: 4.5,
    lightNeed: 8,
  },
  // Aubergines locales
  {
    id: "plantule-aubergine-barbentane",
    plantDefId: "eggplant",
    shopId: "jardiland",
    name: "Aubergine de Barbentane",
    emoji: "🍆",
    price: 80,
    grams: 0,
    description: "Plantule locale — Variété provençale, productive et parfumée",
    image: "/plantules/plantule-aubergine-barbentane.png",
    unlocked: true,
    stageDurations: [10, 24, 25, 55],
    realDaysToHarvest: 114,
    optimalTemp: [20, 30],
    waterNeed: 5.5,
    lightNeed: 8,
  },
  // Salades locales
  {
    id: "plantule-laitue-feuille-chene",
    plantDefId: "lettuce",
    shopId: "gamm-vert",
    name: "Laitue Feuille de Chêne",
    emoji: "🥬",
    price: 55,
    grams: 0,
    description: "Plantule de maraîcher — Feuille croquante, résiste à la chaleur",
    image: "/plantules/plantule-laitue-chene.png",
    unlocked: true,
    stageDurations: [4, 10, 14, 22],
    realDaysToHarvest: 50,
    optimalTemp: [12, 20],
    waterNeed: 3.5,
    lightNeed: 6,
  },
  {
    id: "plantule-laitue-romaine",
    plantDefId: "lettuce",
    shopId: "jardiland",
    name: "Laitue Romaine",
    emoji: "🥬",
    price: 55,
    grams: 0,
    description: "Plantule locale — Coeur ferme et croquant, variety classique",
    image: "/plantules/plantule-laitue-romaine.png",
    unlocked: true,
    stageDurations: [4, 12, 16, 28],
    realDaysToHarvest: 60,
    optimalTemp: [12, 20],
    waterNeed: 3.5,
    lightNeed: 6,
  },
  // Carottes locales
  {
    id: "plantule-carotte-guerande",
    plantDefId: "carrot",
    shopId: "gamm-vert",
    name: "Carotte de Guérande",
    emoji: "🥕",
    price: 70,
    grams: 0,
    description: "Plantule de maraîcher breton — Douce et croquante, sols sableux",
    image: "/plantules/plantule-carotte-guerande.png",
    unlocked: true,
    stageDurations: [10, 28, 26, 52],
    realDaysToHarvest: 116,
    optimalTemp: [15, 22],
    waterNeed: 4.0,
    lightNeed: 6,
  },
  // Fraises locales
  {
    id: "plantule-fraise-gariguette",
    plantDefId: "strawberry",
    shopId: "jardiland",
    name: "Fraise Gariguette",
    emoji: "🍓",
    price: 90,
    grams: 0,
    description: "Plantule locale — La plus parfumée, chair fondante,抢手",
    image: "/plantules/plantule-fraise-gariguette.png",
    unlocked: true,
    stageDurations: [6, 14, 20, 40],
    realDaysToHarvest: 80,
    optimalTemp: [14, 24],
    waterNeed: 4.0,
    lightNeed: 7,
  },
  // Fraises spécialisées locales
  {
    id: "fraise-ostara",
    plantDefId: "strawberry",
    shopId: "pepiniere-locale",
    name: "Fraise Ostara",
    emoji: "🍓",
    price: 92, grams: 0,
    description: "Variété remontante, production de juin jusqu'aux gelées, productive",
    image: "/plantules/plantule-fraise-ostara.png", unlocked: true,
    stageDurations: [6, 14, 20, 45], realDaysToHarvest: 85,
    optimalTemp: [14, 26], waterNeed: 4.0, lightNeed: 7,
  },
  {
    id: "fraise-cirafine",
    plantDefId: "strawberry",
    shopId: "pepiniere-locale",
    name: "Fraise Cirafine",
    emoji: "🍓",
    price: 88, grams: 0,
    description: "Petits fruits allongés, parfum très prononcé, idéale confitures",
    image: "/plantules/plantule-fraise-cirafine.png", unlocked: true,
    stageDurations: [6, 14, 22, 42], realDaysToHarvest: 84,
    optimalTemp: [14, 24], waterNeed: 4.0, lightNeed: 7,
  },
  {
    id: "fraise-rabunda",
    plantDefId: "strawberry",
    shopId: "pepiniere-locale",
    name: "Fraise Rabunda",
    emoji: "🍓",
    price: 85, grams: 0,
    description: "Chair ferme, fruits coniques, bonne conservation, productive",
    image: "/plantules/plantule-fraise-rabunda.png", unlocked: true,
    stageDurations: [6, 14, 20, 40], realDaysToHarvest: 80,
    optimalTemp: [14, 25], waterNeed: 4.0, lightNeed: 7,
  },
  {
    id: "fraise-anabelle",
    plantDefId: "strawberry",
    shopId: "pepiniere-locale",
    name: "Fraise Anabelle",
    emoji: "🍓",
    price: 90, grams: 0,
    description: "Gros fruits ronds, chair juteuse, très sucrée, variété grand terroir",
    image: "/plantules/plantule-fraise-anabelle.png", unlocked: true,
    stageDurations: [6, 14, 22, 45], realDaysToHarvest: 87,
    optimalTemp: [14, 24], waterNeed: 4.0, lightNeed: 7,
  },
  {
    id: "plantule-fraise-mara-des-bois",
    plantDefId: "strawberry",
    shopId: "gamm-vert",
    name: "Fraise Mara des Bois",
    emoji: "🍓",
    price: 95,
    grams: 0,
    description: "Plantule de maraîcher — Parfum intense, petits fruits elongues",
    image: "/plantules/plantule-fraise-mara.png",
    unlocked: true,
    stageDurations: [6, 14, 22, 45],
    realDaysToHarvest: 87,
    optimalTemp: [14, 24],
    waterNeed: 4.0,
    lightNeed: 7,
  },
  // Basilic local
  {
    id: "plantule-basilic-genovee",
    plantDefId: "basil",
    shopId: "gamm-vert",
    name: "Basilic Génovéis",
    emoji: "🌿",
    price: 75,
    grams: 0,
    description: "Plantule de maraîcher — Feuilles larges et parfum intense, le vrai pesto",
    image: "/plantules/plantule-basilic-genovee.png",
    unlocked: true,
    stageDurations: [6, 18, 20, 40],
    realDaysToHarvest: 84,
    optimalTemp: [20, 27],
    waterNeed: 4.0,
    lightNeed: 6,
  },
  // Baies et petits fruits
  {
    id: "plantule-goji-amber-sweet",
    plantDefId: "goji",
    shopId: "les-pepineres-quissac",
    name: "Goji 'Amber Sweet'",
    emoji: "🍒",
    price: 120,
    grams: 0,
    description: "Lycium Barbarum — Baies dorées, douces et sans amertume. Plante vivace",
    image: "/plantules/plantule-goji.png",
    unlocked: true,
    stageDurations: [10, 24, 30, 45],
    realDaysToHarvest: 109,
    optimalTemp: [15, 28],
    waterNeed: 3.5,
    lightNeed: 7,
  },
  {
    id: "plantule-lyciet-rouge",
    plantDefId: "lycium",
    shopId: "les-pepineres-quissac",
    name: "Lyciet Rouge",
    emoji: "🍇",
    price: 110,
    grams: 0,
    description: "Lycium ruthenicum — Petites baies violettes, très résistant au froid",
    image: "/plantules/plantule-lyciet.png",
    unlocked: true,
    stageDurations: [8, 22, 26, 40],
    realDaysToHarvest: 96,
    optimalTemp: [12, 30],
    waterNeed: 3.0,
    lightNeed: 6,
  },
  {
    id: "akebia-shirobana",
    plantDefId: "akebia",
    shopId: "les-pepineres-quissac",
    name: "Akebia Shirobana",
    emoji: "🌸",
    price: 115, grams: 0,
    description: "Vigne chocolat à fleurs blanches, liane ornementale, fruits comestibles",
    image: "/plantules/plantule-akebia-shirobana.png", unlocked: true,
    stageDurations: [14, 28, 40, 60], realDaysToHarvest: 142,
    optimalTemp: [10, 28], waterNeed: 3.5, lightNeed: 6,
  },
  {
    id: "josta-casselier",
    plantDefId: "josta",
    shopId: "les-pepineres-quissac",
    name: "Casselier Josta",
    emoji: "🫐",
    price: 95, grams: 0,
    description: "Ribes x nidigrolaria — Hybride groseille-cassis, gros fruits noirs, saveur unique",
    image: "/plantules/plantule-josta.png", unlocked: true,
    stageDurations: [10, 22, 30, 50], realDaysToHarvest: 112,
    optimalTemp: [10, 25], waterNeed: 4.0, lightNeed: 6,
  },
  {
    id: "baco-noir",
    plantDefId: "baco-noir",
    shopId: "les-pepineres-quissac",
    name: "Baco Noir",
    emoji: "🍇",
    price: 130, grams: 0,
    description: "Vitis labrusca — Vigne interdite hybride, raisin noir rustique, résistant aux maladies",
    image: "/plantules/plantule-baco-noir.png", unlocked: true,
    stageDurations: [14, 30, 50, 90], realDaysToHarvest: 184,
    optimalTemp: [12, 28], waterNeed: 4.0, lightNeed: 8,
  },
  {
    id: "olivier-cailletier",
    plantDefId: "olive",
    shopId: "les-pepineres-quissac",
    name: "Olivier Cailletier",
    emoji: "🫒",
    price: 185, grams: 0,
    description: "Olea europaea — Variété niçoise, olives de table et huile, rustique en méditerranée",
    image: "/plantules/plantule-cailletier.png", unlocked: true,
    stageDurations: [30, 60, 120, 365], realDaysToHarvest: 730,
    optimalTemp: [8, 30], waterNeed: 3.0, lightNeed: 8,
  },
  {
    id: "amelanchier-thiessen",
    plantDefId: "amelanchier",
    shopId: "les-pepineres-quissac",
    name: "Amelanchier Thiessen",
    emoji: "🫐",
    price: 110, grams: 0,
    description: "Amelanchier alnifolia — Myrtille en arbre, gros fruits sucrés, rusticité -40°C",
    image: "/plantules/plantule-amelanchier.png", unlocked: true,
    stageDurations: [12, 25, 40, 70], realDaysToHarvest: 147,
    optimalTemp: [5, 25], waterNeed: 3.5, lightNeed: 7,
  },
  {
    id: "arbousier-rubra",
    plantDefId: "arbousier",
    shopId: "les-pepineres-quissac",
    name: "Arbousier Rubra",
    emoji: "🌸",
    price: 120, grams: 0,
    description: "Arbutus unedo Rubra — Fleurs roses, fruits rouges comestibles, persistant méditerranéen",
    image: "/plantules/plantule-arbousier-rubra.png", unlocked: true,
    stageDurations: [14, 30, 50, 80], realDaysToHarvest: 174,
    optimalTemp: [8, 28], waterNeed: 3.0, lightNeed: 7,
  },
  {
    id: "cassis-blanc-ojeblanc",
    plantDefId: "blackcurrant",
    shopId: "les-pepineres-quissac",
    name: "Cassis Blanc Ojeblanc",
    emoji: "🍇",
    price: 90, grams: 0,
    description: "Ribes nigrum — Cassis blanc, baies jaune pâle douces et parfumées, rare et original",
    image: "/plantules/plantule-cassis-blanc.png", unlocked: true,
    stageDurations: [10, 22, 30, 55], realDaysToHarvest: 117,
    optimalTemp: [10, 22], waterNeed: 4.0, lightNeed: 6,
  },
  {
    id: "akebia-quinata",
    plantDefId: "akebia",
    shopId: "les-pepineres-quissac",
    name: "Akebia quinata",
    emoji: "🍫",
    price: 105, grams: 0,
    description: "Vigne chocolat, liane grimpante, fruits pourpre au goût de coco-cacao",
    image: "/plantules/plantule-akebia-quinata.png", unlocked: true,
    stageDurations: [14, 28, 40, 60], realDaysToHarvest: 142,
    optimalTemp: [10, 28], waterNeed: 3.5, lightNeed: 6,
  },
  {
    id: "plantule-mirabellier-nancy",
    plantDefId: "mirabellier",
    shopId: "pepiniere-locale",
    name: "Mirabellier de Nancy",
    emoji: "🫐",
    price: 150,
    grams: 0,
    description: "Variété de Varmonzey — Chair fine et sucrée, productive et rustique",
    image: "/plantules/plantule-mirabellier.png",
    unlocked: true,
    stageDurations: [18, 35, 55, 80],
    realDaysToHarvest: 188,
    optimalTemp: [10, 25],
    waterNeed: 4.5,
    lightNeed: 7,
  },
  {
    id: "plantule-mirabellier-pointue",
    plantDefId: "mirabellier",
    shopId: "pepiniere-locale",
    name: "Mirabellier Pointue",
    emoji: "🫐",
    price: 155,
    grams: 0,
    description: "Origine Billy-sous-les-Côtes (Meuse) — Chair parfumée, légèrement acidulée",
    image: "/plantules/plantule-mirabellier-pointue.png",
    unlocked: true,
    stageDurations: [18, 35, 55, 80],
    realDaysToHarvest: 188,
    optimalTemp: [10, 25],
    waterNeed: 4.5,
    lightNeed: 7,
  },
  // Arbres fruitiers locaux
  {
    id: "arbre-pommier-reinette",
    plantDefId: "apple",
    shopId: "jardiland",
    name: "Pommier Reinette",
    emoji: "🍎",
    price: 250,
    grams: 0,
    description: "Arbre élevé en pépinière locale — Variété ancienne, chair acidulée",
    image: "/pots/locaux/pot-pommier-reinette.png",
    unlocked: true,
    stageDurations: [30, 60, 120, 360],
    realDaysToHarvest: 730,
    optimalTemp: [8, 22],
    waterNeed: 5.0,
    lightNeed: 7,
  },
  {
    id: "arbre-poirier-comice",
    plantDefId: "pear",
    shopId: "jardiland",
    name: "Poirier Comice",
    emoji: "🍐",
    price: 260,
    grams: 0,
    description: "Arbre élevé en pépinière locale — Chair fondante et sucrée, variété premium",
    image: "/pots/locaux/pot-poirier-comice.png",
    unlocked: true,
    stageDurations: [30, 60, 120, 360],
    realDaysToHarvest: 1095,
    optimalTemp: [7, 24],
    waterNeed: 5.0,
    lightNeed: 7,
  },
  {
    id: "arbre-cerisier-montmorency",
    plantDefId: "cherry",
    shopId: "gamm-vert",
    name: "Cerisier Montmorency",
    emoji: "🍒",
    price: 280,
    grams: 0,
    description: "Arbre de producteur local — Cerise acide parfaite pour tarte et confiture",
    image: "/pots/locaux/pot-cerisier-montmorency.png",
    unlocked: true,
    stageDurations: [30, 60, 120, 360],
    realDaysToHarvest: 1460,
    optimalTemp: [8, 25],
    waterNeed: 4.0,
    lightNeed: 7,
  },
  // Arbustes et petits fruits
  {
    id: "plantule-groseillier",
    plantDefId: "currant",
    shopId: "jardiland",
    name: "Groseillier Rouge",
    emoji: "🍎",
    price: 120,
    grams: 0,
    description: "Arbuste local — Petits fruits acidules, ideales pour confiture",
    image: "/plantules/plantule-groseillier.png",
    unlocked: true,
    stageDurations: [15, 30, 60, 180],
    realDaysToHarvest: 365,
    optimalTemp: [10, 20],
    waterNeed: 3.5,
    lightNeed: 6,
  },
  {
    id: "plantule-murier",
    plantDefId: "blackberry",
    shopId: "gamm-vert",
    name: "Murier Sans Epines",
    emoji: "🫐",
    price: 130,
    grams: 0,
    description: "Plantule de producteur — Baies noires sucrées, sans épines",
    image: "/plantules/plantule-murier.png",
    unlocked: true,
    stageDurations: [15, 30, 60, 180],
    realDaysToHarvest: 365,
    optimalTemp: [12, 24],
    waterNeed: 4.0,
    lightNeed: 7,
  },
  // Plants du marché - échange jardin partagé
  {
    id: "echange-cepes-semis",
    plantDefId: "tomato",
    shopId: "esat-antes",
    name: "Semis de Tomates (Échange)",
    emoji: "🍅",
    price: 0,
    grams: 0,
    description: "Échange gratuit — Semis de tomates variées, provenants de jardiniers locaux",
    image: "/plantules/echange-tomates.png",
    unlocked: true,
    stageDurations: [8, 22, 20, 45],
    realDaysToHarvest: 95,
    optimalTemp: [16, 28],
    waterNeed: 5.0,
    lightNeed: 8,
  },
  {
    id: "echange-salades",
    plantDefId: "lettuce",
    shopId: "esat-antes",
    name: "Plants de Salades (Échange)",
    emoji: "🥬",
    price: 0,
    grams: 0,
    description: "Échange gratuit — Plants de salades diverses, surplus de jardiniers",
    image: "/plantules/echange-salades.png",
    unlocked: true,
    stageDurations: [4, 10, 14, 22],
    realDaysToHarvest: 50,
    optimalTemp: [12, 20],
    waterNeed: 3.5,
    lightNeed: 6,
  },
  // ═══ Jardi E.Leclerc ═══
  {
    id: "plantule-tomate-rouge-grappe",
    plantDefId: "tomato",
    shopId: "jardi-leclerc",
    name: "Tomate Rouge Grappe",
    emoji: "🍅",
    price: 85,
    grams: 0,
    description: "Plantule E.Leclerc — Variété classique, productive et parfumée",
    image: "/plantules/plantule-tomate-grappe.png",
    unlocked: true,
    stageDurations: [8, 22, 20, 45],
    realDaysToHarvest: 95,
    optimalTemp: [16, 28],
    waterNeed: 5.0,
    lightNeed: 8,
  },
  {
    id: "plantule-concombre-americain",
    plantDefId: "cucumber",
    shopId: "jardi-leclerc",
    name: "Concombre Américain",
    emoji: "🥒",
    price: 75,
    grams: 0,
    description: "Plantule E.Leclerc — Fruits longs et lisses, idéal pour salade",
    image: "/plantules/plantule-concombre.png",
    unlocked: true,
    stageDurations: [6, 14, 20, 40],
    realDaysToHarvest: 80,
    optimalTemp: [18, 25],
    waterNeed: 5.0,
    lightNeed: 8,
  },
  {
    id: "plantule-poivron-og主席",
    plantDefId: "pepper",
    shopId: "jardi-leclerc",
    name: "Poivron Rouge",
    emoji: "🌶️",
    price: 80,
    grams: 0,
    description: "Plantule E.Leclerc — Chair épaisse, doux et juteux",
    image: "/plantules/plantule-poivron-rouge.png",
    unlocked: true,
    stageDurations: [10, 26, 26, 58],
    realDaysToHarvest: 120,
    optimalTemp: [20, 28],
    waterNeed: 5.0,
    lightNeed: 8,
  },
  {
    id: "plantule-fraise-ciflorette",
    plantDefId: "strawberry",
    shopId: "jardi-leclerc",
    name: "Fraise Ciflorette",
    emoji: "🍓",
    price: 88,
    grams: 0,
    description: "Plantule E.Leclerc — Chair fondante, sucrée et très parfumée",
    image: "/plantules/plantule-fraise-ciflorette.png",
    unlocked: true,
    stageDurations: [6, 14, 20, 40],
    realDaysToHarvest: 80,
    optimalTemp: [14, 24],
    waterNeed: 4.0,
    lightNeed: 7,
  },
  {
    id: "plantule-basilic-thailandais",
    plantDefId: "basil",
    shopId: "jardi-leclerc",
    name: "Basilic Thailandais",
    emoji: "🌿",
    price: 78,
    grams: 0,
    description: "Plantule E.Leclerc — Arôme citronné, idéal pour cuisine asiatique",
    image: "/plantules/plantule-basilic-thai.png",
    unlocked: true,
    stageDurations: [6, 18, 20, 40],
    realDaysToHarvest: 84,
    optimalTemp: [20, 27],
    waterNeed: 4.0,
    lightNeed: 6,
  },
  {
    id: "plantule-chou-fleur",
    plantDefId: "cabbage",
    shopId: "jardi-leclerc",
    name: "Chou Fleur",
    emoji: "🥬",
    price: 72,
    grams: 0,
    description: "Plantule E.Leclerc — Pommé blanc, riche en vitamine C",
    image: "/plantules/plantule-chou-fleur.png",
    unlocked: true,
    stageDurations: [8, 20, 30, 60],
    realDaysToHarvest: 118,
    optimalTemp: [12, 20],
    waterNeed: 4.5,
    lightNeed: 6,
  },
];

export const SEED_VARIETIES: SeedVariety[] = [
  {
    id: "tomato-cocktail",
    plantDefId: "tomato",
    shopId: "vilmorin",
    name: "Tomate Cocktail",
    emoji: "🍅",
    price: 40,
    grams: 0.5,
    description: "Variété précoce, fruits de 80-100g, saveur sucrée et juteuse. Idéale en salade et grignotage. Très productive.",
    image: "/packets/vilmorin/packet-tomato-cocktail.jpg",
    unlocked: true,
    stageDurations: [8, 22, 20, 45],
    realDaysToHarvest: 95,
    optimalTemp: [16, 28],
    waterNeed: 5.0,
    lightNeed: 8,
  },
  {
    id: "tomato-aneas",
    plantDefId: "tomato",
    shopId: "vilmorin",
    name: "Tomate Anéas",
    emoji: "🍅",
    price: 55,
    grams: 0.3,
    description: "Variété allongée type Roma, fruits de 120-150g, chair dense et peu de graines. Parfaite pour sauces et conserves.",
    image: "/packets/vilmorin/packet-tomato-aneas.png",
    unlocked: true,
    stageDurations: [10, 25, 25, 55],
    realDaysToHarvest: 115,
    optimalTemp: [18, 28],
    waterNeed: 5.5,
    lightNeed: 8,
  },
  // ── Vilmorin — Graines d'Exception 2026 ──
  {
    id: "tomato-lanterna",
    plantDefId: "tomato",
    shopId: "vilmorin",
    name: "Tomate Lanterna HF1",
    emoji: "🍅",
    price: 65, grams: 0.2,
    description: "Nouveauté 2026 — Tomate côtelée, goût prononcé, chair juteuse. Variété Graines d'Exception résistante à la chaleur.",
    image: "/packets/vilmorin/packet-tomato-lanterna.jpg", unlocked: true,
    stageDurations: [8, 22, 25, 50], realDaysToHarvest: 105,
    optimalTemp: [18, 30], waterNeed: 5.5, lightNeed: 8,
  },
  {
    id: "cucumber-marketer-vilmorin",
    plantDefId: "cucumber",
    shopId: "vilmorin",
    name: "Concombre Marketer",
    emoji: "🥒",
    price: 40, grams: 1.5,
    description: "Variété précoce et vigoureuse, fruits de 25cm. Très productive tout l'été.",
    image: "/packets/vilmorin/packet-cucumber-marketer.jpg", unlocked: true,
    stageDurations: [7, 18, 22, 46], realDaysToHarvest: 93,
    optimalTemp: [18, 30], waterNeed: 5.0, lightNeed: 7,
  },
  {
    id: "cucumber-bella",
    plantDefId: "cucumber",
    shopId: "vilmorin",
    name: "Concombre Bella HF1",
    emoji: "🥒",
    price: 70, grams: 0.3,
    description: "Nouveauté 2026 — Parthénocarpique, résistant à la chaleur. Idéal balcon et pleine terre. Graines d'Exception.",
    image: "/packets/vilmorin/packet-cucumber-bella.jpg", unlocked: true,
    stageDurations: [7, 18, 22, 46], realDaysToHarvest: 93,
    optimalTemp: [20, 32], waterNeed: 5.0, lightNeed: 7,
  },
  {
    id: "zucchini-boldenice",
    plantDefId: "zucchini",
    shopId: "vilmorin",
    name: "Courgette Boldenice HF1",
    emoji: "🥒",
    price: 65, grams: 0.3,
    description: "Nouveauté 2026 — Courgette ronde, très productive et facile à cultiver. Graines d'Exception.",
    image: "/packets/vilmorin/packet-zucchini-boldenice.jpg", unlocked: true,
    stageDurations: [7, 18, 25, 46], realDaysToHarvest: 96,
    optimalTemp: [18, 28], waterNeed: 5.0, lightNeed: 7,
  },
  {
    id: "melon-stellio",
    plantDefId: "melon",
    shopId: "vilmorin",
    name: "Melon Stellio HF1",
    emoji: "🍈",
    price: 70, grams: 0.2,
    description: "Nouveauté 2026 — Récolte abondante, fruits sucrés et parfumés. Graines d'Exception.",
    image: "/packets/vilmorin/packet-melon-stellio.jpg", unlocked: true,
    stageDurations: [10, 25, 30, 50], realDaysToHarvest: 115,
    optimalTemp: [20, 32], waterNeed: 5.5, lightNeed: 9,
  },
  {
    id: "melon",
    plantDefId: "melon",
    shopId: "vilmorin",
    name: "Melon",
    emoji: "🍈",
    price: 45, grams: 1.0,
    description: "Variété classique, chairsucrée et parfumée. À cultiver en pleine terre bien amendée.",
    image: "/packets/vilmorin/packet-melon.jpg", unlocked: true,
    stageDurations: [6, 15, 14, 20], realDaysToHarvest: 70,
    optimalTemp: [20, 32], waterNeed: 3.5, lightNeed: 7,
  },
  {
    id: "spinach-soyuz",
    plantDefId: "spinach",
    shopId: "vilmorin",
    name: "Épinard Soyuz HF1",
    emoji: "🥬",
    price: 55, grams: 0.5,
    description: "Nouveauté 2026 — Feuilles tendres même en conditions difficiles. Résiste à la montaison. Graines d'Exception.",
    image: "/packets/vilmorin/packet-spinach-soyuz.png", unlocked: true,
    stageDurations: [7, 14, 18, 31], realDaysToHarvest: 70,
    optimalTemp: [8, 22], waterNeed: 4.0, lightNeed: 5,
  },
  {
    id: "radis-expo",
    plantDefId: "radish",
    shopId: "vilmorin",
    name: "Radis de 18 Jours",
    emoji: "🔴",
    price: 25, grams: 3.0,
    description: "Variété ultra-rapide, rond rouge, chair croquante et légèrement piquante. Récolte en 18-25 jours.",
    image: "/packets/vilmorin/packet-radis-expo.png", unlocked: true,
    stageDurations: [3, 6, 9, 24], realDaysToHarvest: 42,
    optimalTemp: [10, 22], waterNeed: 3.5, lightNeed: 6,
  },
  {
    id: "basil-loki",
    plantDefId: "basil",
    shopId: "vilmorin",
    name: "Basilic Loki",
    emoji: "🌿",
    price: 55, grams: 0.2,
    description: "Nouveauté 2026 — Type Genovese, saveur intense et feuillage abondant. Culture aisée. Graines d'Exception.",
    image: "/packets/vilmorin/packet-basil-loki.png", unlocked: true,
    stageDurations: [6, 16, 18, 38], realDaysToHarvest: 78,
    optimalTemp: [20, 28], waterNeed: 4.0, lightNeed: 6,
  },
  {
    id: "parsley-lion",
    plantDefId: "parsley",
    shopId: "vilmorin",
    name: "Persil Lion",
    emoji: "🌿",
    price: 30, grams: 1.5,
    description: "Nouveauté 2026 — Persil frisé, saveurs intenses et culture aisée. Idéal pour taboulé et garniture.",
    image: "/packets/vilmorin/packet-parsley-lion.png", unlocked: true,
    stageDurations: [14, 28, 30, 40], realDaysToHarvest: 112,
    optimalTemp: [12, 22], waterNeed: 3.5, lightNeed: 6,
  },
  // Leaderplant — Haies persistantes
  {
    id: "photinia-louise",
    plantDefId: "photinia",
    shopId: "leaderplant",
    name: "Photinia panaché 'Louise'",
    emoji: "🌿",
    price: 160, grams: 3.0,
    description: "Photinia panaché exclusif. Feuillage tricolore : jeunes pousses rose vif sur fond vert marginé de blanc crème. Persistant, compact.",
    image: "/packets/leaderplant/packet-photinia-louise.png", unlocked: true,
    stageDurations: [21, 42, 62, 95], realDaysToHarvest: 220,
    optimalTemp: [5, 30], waterNeed: 3.0, lightNeed: 6,
  },
  {
    id: "photinia-red-robin",
    plantDefId: "photinia",
    shopId: "leaderplant",
    name: "Photinia Red Robin",
    emoji: "🌿",
    price: 140, grams: 3.0,
    description: "Haie persistante étoile. Jeunes feuilles rouge écarlate, puis vert foncé brillant. Croissance rapide 40-60cm/an.",
    image: "/packets/leaderplant/packet-photinia-red-robin.png", unlocked: true,
    stageDurations: [21, 40, 60, 90], realDaysToHarvest: 211,
    optimalTemp: [5, 30], waterNeed: 3.0, lightNeed: 6,
  },
  {
    id: "eleagnus-gilt-edge",
    plantDefId: "eleagnus",
    shopId: "leaderplant",
    name: "Élagnus 'Gilt Edge'",
    emoji: "🌾",
    price: 130, grams: 3.0,
    description: "Élagnus panaché or. Bordure jaune doré sur feuillage vert, revers argenté. Persistant, résiste au sel et à la sécheresse.",
    image: "/packets/leaderplant/packet-eleagnus-gilt-edge.png", unlocked: true,
    stageDurations: [21, 44, 62, 92], realDaysToHarvest: 219,
    optimalTemp: [5, 35], waterNeed: 2.5, lightNeed: 6,
  },
  {
    id: "eleagnus-ebbingii",
    plantDefId: "eleagnus",
    shopId: "leaderplant",
    name: "Élagnus ebbingei",
    emoji: "🌾",
    price: 120, grams: 3.0,
    description: "Haie persistante robuste. Feuillage argenté revers roux, parfum d'automne. Résiste au sel et à la sécheresse.",
    image: "/packets/leaderplant/packet-eleagnus-ebbingii.png", unlocked: true,
    stageDurations: [21, 45, 60, 90], realDaysToHarvest: 216,
    optimalTemp: [5, 35], waterNeed: 2.5, lightNeed: 6,
  },
  {
    id: "laurus-nobilis",
    plantDefId: "laurus",
    shopId: "leaderplant",
    name: "Laurier Sauce",
    emoji: "🌿",
    price: 110, grams: 2.0,
    description: "Haie persistante aromatique. Feuilles parfumées utilisées en cuisine. Pousse compacte, tailleur docile.",
    image: "/packets/leaderplant/packet-laurus-nobilis.png", unlocked: true,
    stageDurations: [21, 50, 70, 100], realDaysToHarvest: 241,
    optimalTemp: [5, 30], waterNeed: 3.0, lightNeed: 5,
  },
  {
    id: "thuya-smaragd",
    plantDefId: "thuya",
    shopId: "leaderplant",
    name: "Thuya Smaragd",
    emoji: "🌲",
    price: 130, grams: 2.5,
    description: "Conifère persistant compact, cône naturel vert émeraude. Haie brise-vent idéale, croissance 20-30cm/an.",
    image: "/packets/leaderplant/packet-thuya-smaragd.png", unlocked: true,
    stageDurations: [30, 60, 90, 200], realDaysToHarvest: 380,
    optimalTemp: [5, 25], waterNeed: 3.0, lightNeed: 7,
  },
  {
    id: "escallonia-iveyi",
    plantDefId: "escallonia",
    shopId: "leaderplant",
    name: "Escallonia Iveyi",
    emoji: "🌸",
    price: 110, grams: 2.5,
    description: "Haie persistante fleurie. Abondance de fleurs blanches rosées tout l'été. Résiste aux embruns marins.",
    image: "/packets/leaderplant/packet-escallonia-iveyi.png", unlocked: true,
    stageDurations: [18, 35, 55, 90], realDaysToHarvest: 198,
    optimalTemp: [8, 28], waterNeed: 3.5, lightNeed: 7,
  },
  {
    id: "cornus-alba",
    plantDefId: "cornus",
    shopId: "leaderplant",
    name: "Cornouiller Blanc",
    emoji: "🌸",
    price: 100, grams: 2.0,
    description: "Haie décorative, rameaux rouges éclatants en hiver. Feuillage caduc rouge écarlate à l'automne. Très rustique.",
    image: "/packets/leaderplant/packet-cornus-alba.png", unlocked: true,
    stageDurations: [21, 45, 70, 100], realDaysToHarvest: 236,
    optimalTemp: [5, 28], waterNeed: 3.5, lightNeed: 6,
  },
  {
    id: "casseille-hedge",
    plantDefId: "casseille",
    shopId: "leaderplant",
    name: "Casseille (Haie)",
    emoji: "🫐",
    price: 90, grams: 2.0,
    description: "Haie fruitière persistante. Hybride cassissier × groseillier, fruits noirs riches en vitamine C. Attire les auxiliaires.",
    image: "/packets/leaderplant/packet-casseille-hedge.png", unlocked: true,
    stageDurations: [18, 30, 40, 60], realDaysToHarvest: 148,
    optimalTemp: [5, 25], waterNeed: 4.0, lightNeed: 6,
  },
  // Kokopelli - Varietes bio libres
  {
    id: "tomato-cherokee-purple",
    plantDefId: "tomato",
    shopId: "kokopelli",
    name: "Tomate Cherokee Purple",
    emoji: "\ud83c\udf45",
    price: 65, grams: 0.3,
    description: "Variete ancestrale amerindienne, fruits pourpres noirs au gout fume unique",
    image: "/packets/kokopelli/packet-tomato-cherokee-purple.png", unlocked: true,
    stageDurations: [8,24,22,50], realDaysToHarvest: 104,
    optimalTemp: [18,28], waterNeed: 5.0, lightNeed: 8,
  },
  {
    id: "tomato-rose-de-berne",
    plantDefId: "tomato",
    shopId: "kokopelli",
    name: "Tomate Rose de Berne",
    emoji: "\ud83c\udf45",
    price: 70, grams: 0.3,
    description: "Variete suisse ancienne, rose et charnue, douceur exceptionnelle",
    image: "/packets/kokopelli/packet-tomato-rose-de-berne.png", unlocked: true,
    stageDurations: [8,22,23,48], realDaysToHarvest: 101,
    optimalTemp: [18,27], waterNeed: 5.0, lightNeed: 8,
  },
  // Biau Germe - Semences paysannes bio
  {
    id: "tomato-marmande",
    plantDefId: "tomato",
    shopId: "lebiau",
    name: "Tomate Marmande",
    emoji: "\ud83c\udf45",
    price: 60, grams: 0.3,
    description: "La classique du Sud-Ouest, cotelee et parfumee, tres productive",
    image: "/packets/lebiau/packet-tomato-marmande.png", unlocked: true,
    stageDurations: [7,21,21,48], realDaysToHarvest: 97,
    optimalTemp: [18,28], waterNeed: 5.0, lightNeed: 8,
  },
  {
    id: "carrot-guerande",
    plantDefId: "carrot",
    shopId: "lebiau",
    name: "Carotte de Guerande",
    emoji: "\ud83e\udd55",
    price: 45, grams: 0.5,
    description: "Variete bretonne adaptee aux sols sableux, douce et croquante",
    image: "/packets/lebiau/packet-carrot-guerande.png", unlocked: true,
    stageDurations: [10,28,26,52], realDaysToHarvest: 116,
    optimalTemp: [15,22], waterNeed: 4.0, lightNeed: 6,
  },
  // Biau Germe — Graines du moment (avril, semis de printemps)
  {
    id: "bean-coco-paimpol",
    plantDefId: "bean",
    shopId: "lebiau",
    name: "Haricot Coco de Paimpol",
    emoji: "🫘",
    price: 45, grams: 50,
    description: "Variété AOP de Bretagne, demi-sec tendre et fondant. Semis avril-juillet, récolte 60j.",
    image: "/packets/lebiau/packet-bean-coco-paimpol.png", unlocked: true,
    stageDurations: [6,14,20,30], realDaysToHarvest: 70,
    optimalTemp: [15,25], waterNeed: 3.5, lightNeed: 7,
  },
  {
    id: "squash-butternut-musquee",
    plantDefId: "squash",
    shopId: "lebiau",
    name: "Courge Musquée de Provence",
    emoji: "🎃",
    price: 55, grams: 3.0,
    description: "Potiron plat de Provence, chair orange vif et sucrée. Se conserve tout l'hiver. Semis avril-mai.",
    image: "/packets/lebiau/packet-squash-musquee.png", unlocked: true,
    stageDurations: [8,20,30,60], realDaysToHarvest: 118,
    optimalTemp: [18,28], waterNeed: 5.0, lightNeed: 8,
  },
  {
    id: "chard-vert-lyon",
    plantDefId: "lettuce",
    shopId: "lebiau",
    name: "Blette Verte à Cardes",
    emoji: "🥬",
    price: 35, grams: 2.0,
    description: "Cardes larges et tendres, côtes épaisses blanches. Récolte automne-hiver, semis avril-juin.",
    image: "/packets/lebiau/packet-chard-vert-lyon.png", unlocked: true,
    stageDurations: [7,16,22,35], realDaysToHarvest: 80,
    optimalTemp: [12,22], waterNeed: 4.0, lightNeed: 6,
  },
  {
    id: "sunflower-velours",
    plantDefId: "sunflower",
    shopId: "lebiau",
    name: "Tournesol Velours",
    emoji: "🌻",
    price: 40, grams: 5.0,
    description: "Tournesol pollen, nectar pour abeilles. Fleurs géantes dorées, semis avril-juin. Fleurs comestibles.",
    image: "/packets/lebiau/packet-sunflower-velours.png", unlocked: true,
    stageDurations: [7,18,25,50], realDaysToHarvest: 100,
    optimalTemp: [15,30], waterNeed: 3.0, lightNeed: 9,
  },
  {
    id: "corn-pop-rouge",
    plantDefId: "radish",
    shopId: "lebiau",
    name: "Pavot de Californie",
    emoji: "🌺",
    price: 30, grams: 1.0,
    description: "Fleurs écarlates vives, facile et robuste. Semis avril-mai, floraison tout l'été. Mellifère.",
    image: "/packets/lebiau/packet-poppy-californie.png", unlocked: true,
    stageDurations: [7,14,21,40], realDaysToHarvest: 82,
    optimalTemp: [12,28], waterNeed: 2.5, lightNeed: 8,
  },
  // Ferme de Sainte Marthe - Patrimoine varietal
  {
    id: "basil-genoveois",
    plantDefId: "basil",
    shopId: "saintemarthe",
    name: "Basilic Genois",
    emoji: "\ud83c\udf3f",
    price: 50, grams: 0.2,
    description: "Le vrai basilic italien, feuilles petites et parfum intense",
    image: "/packets/sainte-marthe/packet-basil-genoveois.png", unlocked: true,
    stageDurations: [6,18,20,40], realDaysToHarvest: 84,
    optimalTemp: [20,27], waterNeed: 4.0, lightNeed: 6,
  },
  {
    id: "pepper-doux-france",
    plantDefId: "pepper",
    shopId: "saintemarthe",
    name: "Poivron Doux de France",
    emoji: "\ud83c\udf36\ufe0f",
    price: 55, grams: 0.2,
    description: "Poivron traditionnel francais, doux et parfume, rouge a maturite",
    image: "/packets/sainte-marthe/packet-pepper-doux-france.png", unlocked: true,
    stageDurations: [10,28,28,60], realDaysToHarvest: 126,
    optimalTemp: [20,28], waterNeed: 5.5, lightNeed: 8,
  },
  // Clause — Legumes divers
  {
    id: "carrot-nantaise",
    plantDefId: "carrot",
    shopId: "clause",
    name: "Carotte Nantaise",
    emoji: "🥕",
    price: 35, grams: 0.5,
    description: "Variete classique tres douce et tendre, racine cylindrique",
    image: "/packets/clause/packet-carrot-nantaise.png", unlocked: true,
    stageDurations: [8,20,22,58], realDaysToHarvest: 108,
    optimalTemp: [15,22], waterNeed: 4.0, lightNeed: 6,
  },
  {
    id: "lettuce-batavia",
    plantDefId: "lettuce",
    shopId: "clause",
    name: "Laitue Batavia",
    emoji: "🥬",
    price: 25, grams: 0.3,
    description: "Feuilles croquantes et blondes, resistante a la chaleur",
    image: "/packets/clause/packet-lettuce-batavia.png", unlocked: true,
    stageDurations: [4,10,14,22], realDaysToHarvest: 50,
    optimalTemp: [12,20], waterNeed: 3.5, lightNeed: 6,
  },
  {
    id: "cucumber-marketer",
    plantDefId: "cucumber",
    shopId: "clause",
    name: "Concombre Marketer",
    emoji: "🥒",
    price: 40, grams: 0.3,
    description: "Variete productive, fruits lisses et sans amertume",
    image: "/packets/clause/packet-cucumber-marketer.png", unlocked: true,
    stageDurations: [6,14,20,40], realDaysToHarvest: 80,
    optimalTemp: [18,25], waterNeed: 5.0, lightNeed: 8,
  },
  {
    id: "zucchini-black-beauty",
    plantDefId: "zucchini",
    shopId: "clause",
    name: "Courgette Black Beauty",
    emoji: "🥒",
    price: 45, grams: 0.5,
    description: "Variete productive, fruits sombres et tendres",
    image: "/packets/clause/packet-zucchini-black-beauty.png", unlocked: true,
    stageDurations: [6,16,20,42], realDaysToHarvest: 84,
    optimalTemp: [18,28], waterNeed: 5.0, lightNeed: 8,
  },
  {
    id: "pepper-california-wonder",
    plantDefId: "pepper",
    shopId: "clause",
    name: "Poivron California Wonder",
    emoji: "🌶️",
    price: 50, grams: 0.2,
    description: "Type cloche, chair epaisse et douce",
    image: "/packets/clause/packet-pepper-california-wonder.png", unlocked: true,
    stageDurations: [10,26,26,58], realDaysToHarvest: 120,
    optimalTemp: [20,28], waterNeed: 5.0, lightNeed: 8,
  },
  // Kokopelli — Semences bio ancestrales
  {
    id: "tomato-blackk",
    plantDefId: "tomato",
    shopId: "kokopelli",
    name: "Tomate Noire de Crimee",
    emoji: "🍅",
    price: 65, grams: 0.3,
    description: "Variete noire ancienne, chair Dense et sucree",
    image: "/packets/kokopelli/packet-tomato-blackk.png", unlocked: true,
    stageDurations: [8,24,22,52], realDaysToHarvest: 106,
    optimalTemp: [18,28], waterNeed: 5.0, lightNeed: 8,
  },
  {
    id: "tomato-green-zebra",
    plantDefId: "tomato",
    shopId: "kokopelli",
    name: "Tomate Green Zebra",
    emoji: "🍅",
    price: 60, grams: 0.3,
    description: "Tomate verte rayee, aciditee Balancee, originale en salade",
    image: "/packets/kokopelli/packet-tomato-green-zebra.png", unlocked: true,
    stageDurations: [8,22,20,46], realDaysToHarvest: 96,
    optimalTemp: [17,27], waterNeed: 5.0, lightNeed: 8,
  },
  {
    id: "eggplant-long-violette",
    plantDefId: "eggplant",
    shopId: "kokopelli",
    name: "Aubergine Longue Violette",
    emoji: "🍆",
    price: 50, grams: 0.2,
    description: "Variete productive et precoce, fruits allonges",
    image: "/packets/kokopelli/packet-eggplant-long-violette.png", unlocked: true,
    stageDurations: [8,20,24,50], realDaysToHarvest: 102,
    optimalTemp: [20,28], waterNeed: 5.0, lightNeed: 8,
  },
  {
    id: "squash-butternut-coco",
    plantDefId: "squash",
    shopId: "kokopelli",
    name: "Courge Butternut Coco",
    emoji: "🎃",
    price: 55, grams: 0.5,
    description: "Variete储藏耐, chair douce et sucree, fruits de 1-2kg",
    image: "/packets/kokopelli/packet-squash-butternut-coco.png", unlocked: true,
    stageDurations: [8,24,32,80], realDaysToHarvest: 144,
    optimalTemp: [18,28], waterNeed: 5.5, lightNeed: 8,
  },
  // Kokopelli — Variétés ancestrales bio
  {
    id: "quinoa-tempe",
    plantDefId: "quinoa",
    shopId: "kokopelli",
    name: "Quinoa Tempe",
    emoji: "🌾",
    price: 60, grams: 5.0,
    description: "Quinoa ancestral andin, graines riches en protéines. Semis printemps, récolte en 100j. Graines reproductibles.",
    image: "/packets/kokopelli/packet-quinoa-tempe.png", unlocked: true,
    stageDurations: [7, 20, 30, 50], realDaysToHarvest: 107,
    optimalTemp: [12, 25], waterNeed: 3.0, lightNeed: 7,
  },
  {
    id: "amaranth-red-garnet",
    plantDefId: "amaranth",
    shopId: "kokopelli",
    name: "Amarante Red Garnet",
    emoji: "🌺",
    price: 55, grams: 1.0,
    description: "Amarante ornementale et comestible, panicules rouges écarlates. Graines riches en fer. Semis avril-juin.",
    image: "/packets/kokopelli/packet-amaranth-red-garnet.png", unlocked: true,
    stageDurations: [7, 18, 25, 45], realDaysToHarvest: 95,
    optimalTemp: [18, 30], waterNeed: 3.0, lightNeed: 8,
  },
  {
    id: "bean-coco-rouge",
    plantDefId: "bean",
    shopId: "kokopelli",
    name: "Haricot Coco Rouge",
    emoji: "🫘",
    price: 40, grams: 50,
    description: "Haricot nain coco rouge, grains ronds cramoisis. Très fondant, cuisson rapide. Semis avril-juillet.",
    image: "/packets/kokopelli/packet-bean-coco-rouge.png", unlocked: true,
    stageDurations: [6, 14, 20, 30], realDaysToHarvest: 70,
    optimalTemp: [15, 25], waterNeed: 3.5, lightNeed: 7,
  },
  {
    id: "corn-miel-jaune",
    plantDefId: "corn",
    shopId: "kokopelli",
    name: "Maïs Doux Miel",
    emoji: "🌽",
    price: 50, grams: 15,
    description: "Maïs doux jaune ancien, épis de 20cm, grains sucrés. Semis avril-mai, récolte 110j. Pollinisation croisée.",
    image: "/packets/kokopelli/packet-corn-miel-jaune.png", unlocked: true,
    stageDurations: [7, 20, 30, 55], realDaysToHarvest: 112,
    optimalTemp: [16, 28], waterNeed: 5.0, lightNeed: 8,
  },
  {
    id: "sorrel-oseille-commune",
    plantDefId: "sorrel",
    shopId: "kokopelli",
    name: "Oseille Commune",
    emoji: "🥬",
    price: 35, grams: 2.0,
    description: "Oseille de nos grand-mères, feuilles acidulées. Vivace, repousse chaque printemps. Semis mars-avril.",
    image: "/packets/kokopelli/packet-sorrel-commune.png", unlocked: true,
    stageDurations: [7, 15, 20, 30], realDaysToHarvest: 72,
    optimalTemp: [10, 22], waterNeed: 3.5, lightNeed: 5,
  },
  {
    id: "sunflower-titania",
    plantDefId: "sunflower",
    shopId: "kokopelli",
    name: "Tournesol Titania",
    emoji: "🌻",
    price: 40, grams: 5.0,
    description: "Tournesol pollen bio, fleurs géantes dorées. Attractif pour abeilles et oiseaux. Semis avril-juin.",
    image: "/packets/kokopelli/packet-sunflower-titania.png", unlocked: true,
    stageDurations: [7, 18, 25, 50], realDaysToHarvest: 100,
    optimalTemp: [15, 30], waterNeed: 3.0, lightNeed: 9,
  },
  // Biau Germe — Semences paysannes
  {
    id: "carrot-robver",
    plantDefId: "carrot",
    shopId: "lebiau",
    name: "Carotte Rob Ver",
    emoji: "🥕",
    price: 45, grams: 0.5,
    description: "Carotte hollandaise rouge-orange, tres douce et sucree",
    image: "/packets/lebiau/packet-carrot-robver.png", unlocked: true,
    stageDurations: [9,22,24,55], realDaysToHarvest: 110,
    optimalTemp: [15,22], waterNeed: 4.0, lightNeed: 6,
  },
  {
    id: "lettuce-chene",
    plantDefId: "lettuce",
    shopId: "lebiau",
    name: "Laitue Feuille de Chene",
    emoji: "🥬",
    price: 30, grams: 0.3,
    description: "feuilles tendres et lobees, resistante a la chaleur",
    image: "/packets/lebiau/packet-lettuce-chene.png", unlocked: true,
    stageDurations: [4,10,12,24], realDaysToHarvest: 50,
    optimalTemp: [12,20], waterNeed: 3.5, lightNeed: 6,
  },
  {
    id: "bean-coco",
    plantDefId: "bean",
    shopId: "lebiau",
    name: "Haricot Coco Blanc",
    emoji: "🫘",
    price: 35, grams: 0.4,
    description: "Haricot blanc nain, grainier et savoureux",
    image: "/packets/lebiau/packet-bean-coco.png", unlocked: true,
    stageDurations: [6,14,18,30], realDaysToHarvest: 68,
    optimalTemp: [16,24], waterNeed: 4.5, lightNeed: 8,
  },
  {
    id: "cabbage-milan",
    plantDefId: "cabbage",
    shopId: "lebiau",
    name: "Chou de Milan",
    emoji: "🥬",
    price: 40, grams: 0.3,
    description: "Chou pommele rustique, resistant au froid",
    image: "/packets/lebiau/packet-cabbage-milan.png", unlocked: true,
    stageDurations: [7,20,28,70], realDaysToHarvest: 125,
    optimalTemp: [12,18], waterNeed: 4.0, lightNeed: 6,
  },
  // Biau Germe — Nouvelles varietes 2026
  {
    id: "zucchini-verte-milan-black-beauty",
    plantDefId: "zucchini",
    shopId: "lebiau",
    name: "Courgette Verte de Milan Black Beauty",
    emoji: "🥒",
    price: 40, grams: 2.0,
    description: "Variete italienne classique, fruits vert sombre allonges. Tres productive et fiable, chair tendre.",
    image: "/packets/lebiau/packet-zucchini-verte-milan-black-beauty.png", unlocked: true,
    stageDurations: [7,16,20,44], realDaysToHarvest: 87,
    optimalTemp: [18,28], waterNeed: 5.0, lightNeed: 7,
  },
  {
    id: "zucchini-verte-italie",
    plantDefId: "zucchini",
    shopId: "lebiau",
    name: "Courgette Verte d'Italie",
    emoji: "🥒",
    price: 38, grams: 2.0,
    description: "Courgette cylindrique vert clair rayee, chair fondante et douce. Variete paysanne reproductible.",
    image: "/packets/lebiau/packet-zucchini-verte-italie.png", unlocked: true,
    stageDurations: [7,18,22,45], realDaysToHarvest: 92,
    optimalTemp: [18,28], waterNeed: 5.0, lightNeed: 7,
  },
  {
    id: "squash-striped-cushaw",
    plantDefId: "squash",
    shopId: "lebiau",
    name: "Gourge Striped Cushaw",
    emoji: "🎃",
    price: 55, grams: 3.0,
    description: "Variete ancienne en col de cygne, rayee de vert. Chair orange sucree, saveur de chataigne. Excellente conservation.",
    image: "/packets/lebiau/packet-squash-striped-cushaw.png", unlocked: true,
    stageDurations: [8,22,30,65], realDaysToHarvest: 125,
    optimalTemp: [18,30], waterNeed: 5.5, lightNeed: 8,
  },
  {
    id: "eggplant-longue-violette",
    plantDefId: "eggplant",
    shopId: "lebiau",
    name: "Aubergine Longue Violette",
    emoji: "🍆",
    price: 48, grams: 0.2,
    description: "Variete paysanne bio, fruits allonges violet fonce. Chair tendre et fondante, semences reproductibles.",
    image: "/packets/lebiau/packet-eggplant-longue-violette.png", unlocked: true,
    stageDurations: [8,20,24,50], realDaysToHarvest: 102,
    optimalTemp: [20,28], waterNeed: 5.0, lightNeed: 8,
  },
  {
    id: "pepper-doux-espagne",
    plantDefId: "pepper",
    shopId: "lebiau",
    name: "Poivron Doux d'Espagne",
    emoji: "🌶️",
    price: 50, grams: 0.3,
    description: "Variete traditionnelle espagnole, gros fruits coniques rouges a maturite. Chair epaisse et douce. Semences paysannes.",
    image: "/packets/lebiau/packet-pepper-doux-espagne.png", unlocked: true,
    stageDurations: [10,26,28,58], realDaysToHarvest: 122,
    optimalTemp: [20,30], waterNeed: 5.0, lightNeed: 8,
  },
  {
    id: "pepper-ariane",
    plantDefId: "pepper",
    shopId: "lebiau",
    name: "Poivron Ariane",
    emoji: "🌶️",
    price: 55, grams: 0.2,
    description: "Poivron orange vif, tres productif et precoce. Chair croquante et sucree, fruits coniques de taille moyenne.",
    image: "/packets/lebiau/packet-pepper-ariane.png", unlocked: true,
    stageDurations: [10,25,28,56], realDaysToHarvest: 119,
    optimalTemp: [20,28], waterNeed: 5.0, lightNeed: 8,
  },
  {
    id: "pepper-chocolat",
    plantDefId: "pepper",
    shopId: "lebiau",
    name: "Poivron Chocolat",
    emoji: "🌶️",
    price: 60, grams: 0.2,
    description: "Variete rare au coloris brun chocolat. Saveur exceptionnelle, douce et sucree. Tres appreciee en gastronomie.",
    image: "/packets/lebiau/packet-pepper-chocolat.png", unlocked: true,
    stageDurations: [10,26,28,60], realDaysToHarvest: 124,
    optimalTemp: [20,30], waterNeed: 5.5, lightNeed: 8,
  },
  {
    id: "tomato-raisin-vert",
    plantDefId: "tomato",
    shopId: "lebiau",
    name: "Tomate Raisin Vert",
    emoji: "🍅",
    price: 55, grams: 0.2,
    description: "Tomate grappe verte a maturite, saveur unique acidulee et sucree. Reste verte meme ripe, tres productive.",
    image: "/packets/lebiau/packet-tomato-raisin-vert.png", unlocked: true,
    stageDurations: [7,20,20,46], realDaysToHarvest: 93,
    optimalTemp: [18,28], waterNeed: 4.5, lightNeed: 8,
  },
  {
    id: "tomato-cerisette-brin-muguet",
    plantDefId: "tomato",
    shopId: "lebiau",
    name: "Tomate Cerisette Brin de Muguet",
    emoji: "🍅",
    price: 50, grams: 0.15,
    description: "Cerisette en longues grappes decoratives, fruits minis d'une douceur exceptionnelle. Tres productive et precoce.",
    image: "/packets/lebiau/packet-tomato-cerisette-brin-muguet.png", unlocked: true,
    stageDurations: [7,18,18,44], realDaysToHarvest: 87,
    optimalTemp: [16,28], waterNeed: 4.0, lightNeed: 8,
  },
  {
    id: "cucumber-le-genereux",
    plantDefId: "cucumber",
    shopId: "lebiau",
    name: "Concombre Le Généreux",
    emoji: "🥒",
    price: 42, grams: 1.5,
    description: "Variete paysanne bio tres productive, fruits lisses de bonne taille. Sans amertume. Nomme pour sa generosite.",
    image: "/packets/lebiau/packet-cucumber-le-genereux.png", unlocked: true,
    stageDurations: [7,16,20,44], realDaysToHarvest: 87,
    optimalTemp: [18,28], waterNeed: 5.0, lightNeed: 7,
  },
  {
    id: "cucumber-rollisons-telegraph",
    plantDefId: "cucumber",
    shopId: "lebiau",
    name: "Concombre Rollison's Telegraph",
    emoji: "🥒",
    price: 48, grams: 1.0,
    description: "Variete anglaise historique, longs fruits 25-35cm, chair ferme et sans amertume. Excellente en serre.",
    image: "/packets/lebiau/packet-cucumber-rollisons-telegraph.png", unlocked: true,
    stageDurations: [7,18,22,48], realDaysToHarvest: 95,
    optimalTemp: [20,28], waterNeed: 5.0, lightNeed: 7,
  },
  {
    id: "tomato-saint-pierre",
    plantDefId: "tomato",
    shopId: "lebiau",
    name: "Tomate Saint Pierre",
    emoji: "🍅",
    price: 55, grams: 0.3,
    description: "La reference du jardinier francais. Fruit rond, rouge, ferme et gouteux. Tres polyvalente en cuisine.",
    image: "/packets/lebiau/packet-tomato-saint-pierre.png", unlocked: true,
    stageDurations: [8,22,22,50], realDaysToHarvest: 102,
    optimalTemp: [18,28], waterNeed: 5.0, lightNeed: 8,
  },
  {
    id: "tomato-kumato",
    plantDefId: "tomato",
    shopId: "lebiau",
    name: "Tomate Kumato",
    emoji: "🍅",
    price: 65, grams: 0.2,
    description: "Tomate brun-rouge unique, saveur exceptionnelle riche et complexe. Mûrit du vert au brun-rouge. Semences paysannes.",
    image: "/packets/lebiau/packet-tomato-kumato.png", unlocked: true,
    stageDurations: [8,22,22,48], realDaysToHarvest: 100,
    optimalTemp: [18,28], waterNeed: 4.5, lightNeed: 8,
  },
  {
    id: "tomato-evergreen",
    plantDefId: "tomato",
    shopId: "lebiau",
    name: "Tomate Evergreen",
    emoji: "🍅",
    price: 60, grams: 0.2,
    description: "Tomate verte a maturite, saveur sucree et acidulee aux notes d'agrumes. Chair tendre et juteuse. Variete rare.",
    image: "/packets/lebiau/packet-tomato-evergreen.png", unlocked: true,
    stageDurations: [8,22,22,48], realDaysToHarvest: 100,
    optimalTemp: [18,28], waterNeed: 4.5, lightNeed: 8,
  },
  // Sainte Marthe — Aromatiques et autres
  {
    id: "basil-marseillais",
    plantDefId: "basil",
    shopId: "saintemarthe",
    name: "Basilic Marseillais",
    emoji: "🌿",
    price: 50, grams: 0.2,
    description: "Le meilleur basilic pour le pistou,Tres parfume",
    image: "/packets/sainte-marthe/packet-basil-marseillais.png", unlocked: true,
    stageDurations: [6,16,18,38], realDaysToHarvest: 78,
    optimalTemp: [20,27], waterNeed: 4.0, lightNeed: 6,
  },
  {
    id: "strawberry-ciflorette",
    plantDefId: "strawberry",
    shopId: "saintemarthe",
    name: "Fraise Ciflorette",
    emoji: "🍓",
    price: 70, grams: 0.2,
    description: "Fraise allongee tres douce et sucree, originate du Gers",
    image: "/packets/sainte-marthe/packet-strawberry-ciflorette.png", unlocked: true,
    stageDurations: [14,24,30,58], realDaysToHarvest: 126,
    optimalTemp: [14,22], waterNeed: 4.5, lightNeed: 7,
  },
  // Arbres fruitiers — Guignard & INRAE
  {
    id: "apple-golden",
    plantDefId: "apple",
    shopId: "guignard",
    name: "Pommier Golden Delicious",
    emoji: "🍎",
    price: 220, grams: 0.5,
    description: "Variete classic, chair douce et juteuse, Bonne conservation",
    image: "/pots/guignard/pot-apple-golden.png", unlocked: true,
    stageDurations: [30,60,120,360], realDaysToHarvest: 730,
    optimalTemp: [8,22], waterNeed: 5.0, lightNeed: 7,
  },
  {
    id: "apple-gala",
    plantDefId: "apple",
    shopId: "guignard",
    name: "Pommier Gala",
    emoji: "🍎",
    price: 230, grams: 0.5,
    description: "Variete croquante et sucree,tres瑞 populaire",
    image: "/pots/guignard/pot-apple-gala.png", unlocked: true,
    stageDurations: [28,56,110,340], realDaysToHarvest: 700,
    optimalTemp: [8,22], waterNeed: 5.0, lightNeed: 7,
  },
  {
    id: "pear-williams",
    plantDefId: "pear",
    shopId: "guignard",
    name: "Poirier Williams",
    emoji: "🍐",
    price: 240, grams: 0.5,
    description: "Variete tres瑞 ancienne, chair fondante et parfumee",
    image: "/pots/guignard/pot-pear-williams.png", unlocked: true,
    stageDurations: [30,65,130,380], realDaysToHarvest: 800,
    optimalTemp: [10,22], waterNeed: 5.0, lightNeed: 7,
  },
  {
    id: "cherry-bing",
    plantDefId: "cherry",
    shopId: "inrae",
    name: "Cerisier Bing",
    emoji: "🍒",
    price: 260, grams: 0.4,
    description: "Cerise rouge fonce, chair ferme et tres douce et sucree",
    image: "/pots/inrae/cherry-bing-pot.png", unlocked: true,
    stageDurations: [35,70,140,420], realDaysToHarvest: 900,
    optimalTemp: [10,24], waterNeed: 5.0, lightNeed: 7,
  },
  {
    id: "walnut-franquette",
    plantDefId: "walnut",
    shopId: "inrae",
    name: "Noyer Franquette",
    emoji: "🥜",
    price: 200, grams: 0.4,
    description: "Noix de Grenoble, amande parfumee et peu de cerne",
    image: "/packets/inrae/packet-walnut-franquette.png", unlocked: true,
    stageDurations: [40,90,200,600], realDaysToHarvest: 1095,
    optimalTemp: [8,24], waterNeed: 4.5, lightNeed: 6,
  },
  // INRAE - Chene
  {
    id: "oak-pedoncule",
    plantDefId: "oak",
    shopId: "inrae",
    name: "Chene Pedoncule",
    emoji: "🌳",
    price: 200, grams: 2.0,
    description: "Chene commun des forets francaises, croissance lente, bois noble",
    image: "/packets/inrae/packet-oak-pedoncule.png", unlocked: true,
    stageDurations: [60,120,180,1095], realDaysToHarvest: 1455,
    optimalTemp: [8,22], waterNeed: 4.0, lightNeed: 7,
  },
  // Pepinieres Bordas
  {
    id: "maple-acer-platanoides",
    plantDefId: "maple",
    shopId: "pepinieres-bordas",
    name: "Erable Plane",
    emoji: "🍁",
    price: 220, grams: 1.5,
    description: "Erable majestueux, feuillage dore en automne",
    image: "/packets/pepinieres-bordas/packet-maple-platanoides.png", unlocked: true,
    stageDurations: [50,100,150,900], realDaysToHarvest: 1200,
    optimalTemp: [10,22], waterNeed: 4.5, lightNeed: 7,
  },
  // INRAE - Chene
  // Pepinieres Bordas - Arbres d'ornement
  {
    id: "birch-betula",
    plantDefId: "birch",
    shopId: "pepinieres-bordas",
    name: "Bouleau Blanc",
    emoji: "🌲",
    price: 200, grams: 0.8,
    description: "Ecorce blanche decorative, croissance rapide, resistant au froid",
    image: "/packets/pepinieres-bordas/packet-birch-white.png", unlocked: true,
    stageDurations: [40,80,120,730], realDaysToHarvest: 970,
    optimalTemp: [5,20], waterNeed: 4.0, lightNeed: 6,
  },
  {
    id: "pine-sylvestris",
    plantDefId: "pine",
    shopId: "pepinieres-bordas",
    name: "Pin Sylvestre",
    emoji: "🌲",
    price: 200, grams: 1.0,
    description: "Conifere rustique, ecorce orangee, ideal haies brise-vent",
    image: "/packets/pepinieres-bordas/packet-pine-sylvestris.png", unlocked: true,
    stageDurations: [60,120,200,1095], realDaysToHarvest: 1475,
    optimalTemp: [8,20], waterNeed: 3.5, lightNeed: 8,
  },
  {
    id: "magnolia-grandiflora",
    plantDefId: "magnolia",
    shopId: "pepinieres-bordas",
    name: "Magnolia Grandiflora",
    emoji: "🌸",
    price: 300, grams: 2.0,
    description: "Fleurs blanches geantes parfumees, feuillage persistant luisant",
    image: "/packets/pepinieres-bordas/packet-magnolia-grandiflora.png", unlocked: true,
    stageDurations: [70,140,250,1200], realDaysToHarvest: 1660,
    optimalTemp: [12,25], waterNeed: 5.0, lightNeed: 7,
  },
  // Arbres Tissot - Pommiers et Poiriers specialises
  {
    id: "apple-reine-reinettes",
    plantDefId: "apple",
    shopId: "arbres-tissot",
    name: "Pommier Reine des Reinettes",
    emoji: "🍎",
    price: 230, grams: 0.6,
    description: "Variete ancienne rustique, pommes parfumees, excellente conservation",
    image: "/pots/arbres-tissot/pot-apple-reine-reinettes.png", unlocked: true,
    stageDurations: [30,60,120,380], realDaysToHarvest: 750,
    optimalTemp: [8,22], waterNeed: 5.0, lightNeed: 7,
  },
  {
    id: "apple-belle-fleur",
    plantDefId: "apple",
    shopId: "arbres-tissot",
    name: "Pommier Belle Fleur",
    emoji: "🍎",
    price: 220, grams: 0.6,
    description: "Pommes jaunes douces, floraison spectaculaire, tres productive",
    image: "/pots/arbres-tissot/pot-apple-belle-fleur.png", unlocked: true,
    stageDurations: [28,58,115,360], realDaysToHarvest: 720,
    optimalTemp: [8,22], waterNeed: 5.0, lightNeed: 7,
  },
  {
    id: "pear-conference",
    plantDefId: "pear",
    shopId: "arbres-tissot",
    name: "Poirier Conference",
    emoji: "🍐",
    price: 240, grams: 0.7,
    description: "Variete anglaise, chair fondante et sucree, autofertile",
    image: "/pots/arbres-tissot/pot-pear-conference.png", unlocked: true,
    stageDurations: [32,65,130,400], realDaysToHarvest: 820,
    optimalTemp: [10,22], waterNeed: 5.0, lightNeed: 7,
  },
  {
    id: "pear-louise-bonne",
    plantDefId: "pear",
    shopId: "arbres-tissot",
    name: "Poirier Louise Bonne",
    emoji: "🍐",
    price: 230, grams: 0.7,
    description: "Poire ancienne fondante, chair blanche juteuse, tres parfumee",
    image: "/pots/arbres-tissot/pot-pear-louise-bonne.png", unlocked: true,
    stageDurations: [30,62,125,390], realDaysToHarvest: 800,
    optimalTemp: [10,22], waterNeed: 5.0, lightNeed: 7,
  },
  // Fruitiers Forest - Fruits a noyau et specialites
  {
    id: "apricot-bergeron",
    plantDefId: "apricot",
    shopId: "fruitiers-forest",
    name: "Abricotier Bergeron",
    emoji: "🍑",
    price: 250, grams: 0.8,
    description: "Variete du Roussillon, fruits gros et parfumes, chair ferme",
    image: "/packets/fruitiers-forest/packet-apricot-bergeron.png", unlocked: true,
    stageDurations: [35,70,140,420], realDaysToHarvest: 850,
    optimalTemp: [10,25], waterNeed: 4.5, lightNeed: 8,
  },
  {
    id: "plum-reine-claude",
    plantDefId: "plum",
    shopId: "fruitiers-forest",
    name: "Prunier Reine Claude",
    emoji: "🍑",
    price: 220, grams: 0.6,
    description: "Prune verte doree, chair sucree et fondante, variete royale",
    image: "/packets/fruitiers-forest/packet-plum-reine-claude.png", unlocked: true,
    stageDurations: [28,56,110,340], realDaysToHarvest: 680,
    optimalTemp: [10,24], waterNeed: 4.5, lightNeed: 7,
  },
  {
    id: "fig-goutte-or",
    plantDefId: "fig",
    shopId: "fruitiers-forest",
    name: "Figuier Goutte d'Or",
    emoji: "🫐",
    price: 210, grams: 0.5,
    description: "Figues jaunes tres sucrees, chair rose, bifere",
    image: "/packets/fruitiers-forest/packet-fig-goutte-or.png", unlocked: true,
    stageDurations: [40,80,160,500], realDaysToHarvest: 950,
    optimalTemp: [12,28], waterNeed: 4.0, lightNeed: 8,
  },
  {
    id: "peach-sanguine",
    plantDefId: "peach",
    shopId: "fruitiers-forest",
    name: "Pecher Sanguine de Savoie",
    emoji: "🍑",
    price: 240, grams: 0.7,
    description: "Peche chair rouge sang, sucree et parfumee, variete ancienne",
    image: "/packets/fruitiers-forest/packet-peach-sanguine.png", unlocked: true,
    stageDurations: [32,65,130,400], realDaysToHarvest: 820,
    optimalTemp: [10,26], waterNeed: 5.0, lightNeed: 8,
  },
  {
    id: "quince-champion",
    plantDefId: "quince",
    shopId: "fruitiers-forest",
    name: "Cognassier Champion",
    emoji: "🍋",
    price: 200, grams: 0.6,
    description: "Coings gros et parfumes, ideal gelees et pates de fruits",
    image: "/packets/fruitiers-forest/packet-quince-champion.png", unlocked: true,
    stageDurations: [35,70,140,420], realDaysToHarvest: 850,
    optimalTemp: [10,24], waterNeed: 4.5, lightNeed: 7,
  },
  // Arbres Tissot - Pommiers et Poiriers specialises
  // Fruitiers Forest - Fruits a noyau et specialites
];

export interface Achievement {
  id: string;
  name: string;
  desc: string;
  unlocked: boolean;
  icon: string;
  dateUnlocked?: number;
}

const INITIAL_ACHIEVEMENTS: Achievement[] = [
  { id: "green_thumb", name: "Main Verte", desc: "Récolter 50 plantes", unlocked: false, icon: "🌱" },
  { id: "weather_master", name: "Maître Météo", desc: "Jouer sous la pluie 5 fois", unlocked: false, icon: "🌧️" },
  { id: "night_owl", name: "Hibou", desc: "Jouer après 22h", unlocked: false, icon: "🦉" },
];

export interface SeedItem {
  id: string;
  plantDefId: string;
  name: string;
  emoji: string;
  price: number;
  brand: string;         // Fournisseur (Vilmorin, Clause…)
  packetImage: string;   // Image packet/paquet avec marque
  cardImage: string;    // Image de la seed card
  realDaysToHarvest: number;
  optimalMonths: number[];
  category: "vegetable" | "fruit-tree" | "aromatic";
}

// Seed packets avec marque fournisseur — par categorie
export const SEED_CATALOG: SeedItem[] = [
  // Graines classiques (paquets generiques) — prix rééquilibrés
  { id:"seed-tomato",     plantDefId:"tomato",     name:"Paquet Graines Tomate",   emoji:"🍅", price:25, brand:"Vilmorin",  packetImage:"/packets/card-tomato.png",     cardImage:"/cards/card-tomato.png",     realDaysToHarvest:109, optimalMonths:[2,3,4],        category:"vegetable" },
  { id:"seed-carrot",     plantDefId:"carrot",     name:"Paquet Graines Carotte",  emoji:"🥕", price:20, brand:"Clause",    packetImage:"/packets/card-carrot.png",     cardImage:"/cards/card-carrot.png",     realDaysToHarvest:114, optimalMonths:[2,3,4,5,8,9],  category:"vegetable" },
  { id:"seed-strawberry", plantDefId:"strawberry", name:"Paquet Graines Fraise",   emoji:"🍓", price:35, brand:"Truffaut",  packetImage:"/packets/card-strawberry.png", cardImage:"/cards/card-strawberry.png", realDaysToHarvest:123, optimalMonths:[2,3,4,8,9],    category:"vegetable" },
  { id:"seed-lettuce",    plantDefId:"lettuce",    name:"Paquet Graines Salade",   emoji:"🥬", price:15, brand:"Jardiland", packetImage:"/packets/card-lettuce.png",    cardImage:"/cards/card-lettuce.png",    realDaysToHarvest:49,  optimalMonths:[1,2,3,4,8,9,10], category:"vegetable" },
  { id:"seed-basil",      plantDefId:"basil",      name:"Paquet Graines Basilic",  emoji:"🌿", price:25, brand:"St Marthe", packetImage:"/packets/card-basil.png",      cardImage:"/cards/card-basil.png",      realDaysToHarvest:88,  optimalMonths:[3,4,5],        category:"aromatic" },
  { id:"seed-pepper",     plantDefId:"pepper",     name:"Paquet Graines Piment",   emoji:"🌶️", price:30, brand:"Kokopelli", packetImage:"/packets/card-pepper.png",     cardImage:"/cards/card-pepper.png",     realDaysToHarvest:130, optimalMonths:[1,2,3,4],      category:"vegetable" },
];

// Auto-resolve image path from item id + type (new items auto-get their path)
export function resolveItemImage(itemId: string, type: string): string {
  if (type === "variety") return "/cards/" + itemId + ".png";
  if (type === "seed")    return "/packets/" + itemId + ".png";
  if (type === "plantule") return "/cards/" + itemId + ".png";
  return "/cards/card-unknown.png";
}
export function resolvePacketImage(id: string): string { return "/packets/" + id + ".png"; }
export function resolveCardImage(id: string): string { return "/cards/" + id + ".png"; }

// Auto-assign brand from shop or plant type
export const DEFAULT_BRANDS = ["Vilmorin","Clause","Truffaut","Jardiland","St Marthe","Kokopelli","Biau Germe","Guignard","INRAE"];
export function autoBrandFor(plantDefId: string, shopId?: string): string {
  if (shopId) { const s = SEED_SHOPS.find((x) => x.id === shopId); if (s) return s.name; }
  const m: Record<string,string> = {tomato:"Vilmorin",carrot:"Clause",lettuce:"Jardiland",strawberry:"Truffaut",basil:"St Marthe",pepper:"Kokopelli",apple:"Guignard",pear:"Guignard",cherry:"INRAE",walnut:"INRAE",oak:"INRAE"};
  return m[plantDefId] || DEFAULT_BRANDS[Math.floor(Math.random() * DEFAULT_BRANDS.length)];
}

// Auto image path for any new boutique item
export function autoImagePath(itemId: string, type: string): string {
  const slug = itemId.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+$/, "");
  return type === "packet" ? "/packets/" + slug + ".png" : "/cards/" + slug + ".png";
}

// Equipment cards
export const EQUIPMENT_CARDS = [
  { id:"greenhouse",     name:"Serre de Jardin",          emoji:"🏠", cardImage:"/equipment/serre-de-jardin.png",  type:"serre" },
  { id:"mini-serre",     name:"Mini Serre (24 slots)",    emoji:"🌱", cardImage:"/cards/card-mini-serre.png",     type:"equipment" },
  { id:"chambre-small",  name:"Chambre de Culture 60cm",  emoji:"📦", cardImage:"/cards/card-chambre-small.png",  type:"equipment" },
  { id:"chambre-medium", name:"Chambre de Culture 80cm",  emoji:"📦", cardImage:"/cards/card-chambre-medium.png", type:"equipment" },
  { id:"chambre-large",  name:"Chambre de Culture 120cm", emoji:"🛖", cardImage:"/cards/card-chambre-large.png",  type:"equipment" },
];

export interface PlantuleItem {
  plantDefId: string;
  name: string;
  emoji: string;
  price: number;
}

export const PLANTULE_CATALOG: PlantuleItem[] = [
  { plantDefId: "tomato", name: "Plantule Tomate", emoji: "🍅", price: 50 },
  { plantDefId: "carrot", name: "Plantule Carotte", emoji: "🥕", price: 40 },
  { plantDefId: "strawberry", name: "Plantule Fraise", emoji: "🍓", price: 55 },
  { plantDefId: "lettuce", name: "Plantule Salade", emoji: "🥬", price: 30 },
  { plantDefId: "basil", name: "Plantule Basilic", emoji: "🌿", price: 45 },
  { plantDefId: "pepper", name: "Plantule Piment", emoji: "🌶️", price: 50 },
];

// ═══ Custom cards loader (from admin panel) ═══
export async function loadCustomCards(): Promise<{
  customShops: SeedShop[];
  customVarieties: SeedVariety[];
  customPlantules: PlantuleItem[];
  customSeeds: SeedItem[];
}> {
  try {
    const res = await fetch("/data/custom-cards.json?t=" + Date.now());
    if (!res.ok) throw new Error("Not found");
    const data = await res.json();
    return {
      customShops: (data.shops || []) as SeedShop[],
      customVarieties: (data.varieties || []) as SeedVariety[],
      customPlantules: (data.plantules || []) as PlantuleItem[],
      customSeeds: (data.seeds || []) as SeedItem[],
    };
  } catch {
    return { customShops: [], customVarieties: [], customPlantules: [], customSeeds: [] };
  }
}
